Rebase on v0.11.0
appsembler/edx-sga pull request #6
Opened 2022-02-04 09:53 UTC by shadinaif

## Change description

Rebase on upstream v0.11.0

## Type of change
- [ ] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Related issues

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2022-02-04 12:41 UTC, OmarIthawi requested changes
@shadinaif `rebase` rewrites history, so it's not really fit in this case.

Please make a PR that does `merge` instead.

```
git checkout upstream/v0.11.0
git checkout -b shadi/v0.11.0
git push -u origin shadi/v0.11.0
```

Open a PR from `shadi/v0.11.0` into `master`

2022-02-09 10:26 UTC, shadinaif commented
History restored as requested @OmarIthawi

2022-02-09 11:34 UTC, OmarIthawi approved these changes

2022-02-09 14:16 UTC, thraxil approved these changes

2022-02-10 10:09 UTC, merged